[package]
name = "egui"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
eframe = "0.31.1"
env_logger = "0.11.8"
rfd = "0.15.3"
rusqlite = { version = "0.37.0", features = ["bundled"] }
