[package]
name = "catalogo-eletrico-de-precos"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
csv = "1.3.1"
eframe = "0.31.1"
env_logger = "0.11.8"
num-format = "0.4.4"
rfd = "0.15.3"
rusqlite = { version = "0.37.0", features = ["bundled"] }
